services:
  whisper-server:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "61020:61020"
      - "65432:65432"
    environment:
    - HOST=0.0.0.0
    - PORT=61020